baseurl: https://rleanalytics.com
languageCode: en-us
defaultContentLanguage: en
isMultilingual: no
title: RLE Analytics
theme: hugo-theme-sam
pygmentsStyle: monokai
pygmentsCodefences: yes
params:
  dateform: Mon Jan 02, 2006
  dateformfull: Mon Jan 2 2006 15:04:05 EST
  description: RLE Analytics
  favicon: sam.ico
  footerText: RLE Analytics
  homepage: main
  images: tn.png
  mainMenu:
    # - link: posts
    #   text: posts
    # - link: gallery
    #   text: gallery
    # - link: portfolio
    #   text: portfolio
    # - link: about
    #   text: about
    - link: 
      text: RLE Analytics
  title: RLE Analytics
  videoBackground:
    overlay: rgba(0, 0, 0, 0.4)
    sources:
      - poster: /background.png
        source: /sample_video.mp4
        type: video/mp4
imaging:
  quality: 75
